[WIP] Add int and float management for cleanQuantity script and add tests
arkhn/cleaning-scripts pull request #42
Opened 2020-10-14 13:08 UTC by nriss

## Description

If a value is saved in int or float, it will not be modified by cleanQuantity and won't return an error.
Addition of cleanQuantity tests

2020-10-14 14:03 UTC, LaRiffle approved these changes

2020-10-14 14:03 UTC, LaRiffle commented on scripts/custom/clean_quantity.py
> +    if isinstance(raw_input, float) or isinstance(raw_input, int):
```suggestion
    if isinstance(raw_input, (float, int)):
```

2020-10-14 14:07 UTC, elsiehoffet-94 requested changes
Don't forget to change the version in setup.py

2020-10-14 14:11 UTC, Jasopaum reviewed
I'm not sure this script is still needed as it basically casts inputs to float and this work is already done by river when needed.
I'm not saying we should totally remove it because some mappings rely on though...

2020-10-15 08:15 UTC, simonvadee reviewed
as @elsiehoffet-94 said, fon't forget the version.
I agree with @Jasopaum, if the sql column is already of type int/float, the script clean_quantity should not be used since river does not cast the value as a string.

2020-10-15 08:21 UTC, nriss commented
> river does not cast the value as a string.

I suggest to change the description of the cleaning script
`Removes input not conform to FHIR quantity type`
To
`[deprecated: river parses types automatically] Removes input not conform to FHIR quantity type`

2020-10-15 08:34 UTC, simonvadee approved these changes

2020-10-15 09:10 UTC, elsiehoffet-94 approved these changes

2020-10-15 09:30 UTC, merged